on: [push]

jobs: 
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run action
        id: hello
        uses: ./.github/actions/container-actions
        with:
          myInput: "James Smith"
      - name: Output
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "total memory successful output"
      

